### ISSUE TITLE
[WadScript] Executor in DoomTools GUI not Respecting Working Directory (Form Issue?)

### ISSUE THREAD

**Issue by MFG38** [MTrop/DoomTools#87] opened 2023-01-15 15:41 UTC
**Version of DoomTools:** 2023-01-14
**Installation method:** Full installer
**OS:** Windows 10

**Description of issue:**
The WadScript executor program has a fatal flaw where it tries to read the first line of the script file, which is a comment line, as actual code and thus aborts with the following error:

`ERROR: Script could not be started: (C:\Users\Santtu\Documents\GitHub\coldwire\scripts\merge-respack.wscript) Line 1, Token "################################################################": Not a valid directive: ################################################################`

What's interesting is that this issue is exclusive to the WadScript executor. Opening the file in the WadScript editor and running it through that does not produce this problem.

**Comment by MFG38** [comment] 2023-01-15 15:52
Ignore. I was a dumbass and trying to run the script using the wrong executor. It's WadMerge, not WadScript.

**Comment by MFG38** [comment] 2023-01-15 16:07
Actually there _is_ still a problem. The script successfully produces an output .wad when run through the WadMerge script editor, but trying to run it through the execution dialog produces the following error:

`ERROR: C:\Users\Santtu\Documents\GitHub\coldwire\scripts\merge-respack.wadm, line 10: Command mergedir returned BAD_DIRECTORY.`

Just to double-check, I tried to run the script setting the working directory to every directory within the project folder, including the root folder, and it produced the same error in all cases.

**Comment by MTrop** [comment] 2023-01-16 15:52
So you have some sample code? How is line 10 of that file written?

**Comment by MFG38** [comment] 2023-01-16 16:32
Done. The specific file that's causing the problem is this one:
https://github.com/MFG38/coldwire/blob/main/scripts/merge-respack.txt

**Comment by MTrop** [comment] 2023-01-16 17:26
For my notes: This is the Executor in the DoomTools Desktop. Set issue to "bug".

**Comment by MTrop** [comment] 2023-01-16 17:50
So, it looks like it *is* respecting the working directory, but there may be an underlying form issue screwing with things. May need to investigate further, and see what other forms are affected.

**Comment by MTrop** [comment] 2023-01-16 18:17
Made commit 4cf46cc74541e4561600c4a8fba180fa0dd0ccd1 in the hopes of helping this issue. Leaving this issue open until I can confirm it is fixed.

I unfortunately cannot replicate it, otherwise.

**Comment by MFG38** [comment] 2023-01-25 17:29
Issue appears to be fixed. Cheers!

**Comment by MTrop** [comment] 2023-01-25 17:30
Yay! Closing ticket.

**Closed by MTrop** 2023-01-25 17:30 UTC
Labels: bug, high priority, need more feedback, can't reproduce
