### ISSUE TITLE
WadMerge mergedir Behavior

### ISSUE THREAD

**Issue by sponge** [MTrop/DoomTools#2] opened 2020-07-22 20:54 UTC
Currently, `wadmerge` creates markers for each subdirectory, and places the files in that directory underneath that marker. However, files at the top level of the directory may appear under other markers, based on what appears to be alphabetical order.

```
marker w \GFX
mergedir w gfx
```

with a gfx folder that looks like:

- gfx
    - interpic.lmp
    - titlepic.lmp
    - boom
        - (files)
    - inter
        - (files)

will generate a WAD file where the lumps are ordered:
```
\GFX
\BOOM
(files underneath boom folder)
\INTER
(files underneath inter folder)
INTERPIC
TITLEPIC
```

This implies that `INTERPIC` and `TITLEPIC` can be found inside the inter folder, however they are at the top level. My expectation was that files at the top level of `mergedir` are added at the current position underneath the `\GFX` marker I created, and then all subdirectories are in order after that. Otherwise to maintain the meaning of the markers, there must not be any loose files at the top directory of a `mergedir`

**Comment by MTrop** [comment] 2020-07-22 22:54
Closing this one. Exact duplicate of https://github.com/MTrop/DoomTools/issues/1, probably made accidentally.

**Closed by MTrop** 2020-07-22 22:54 UTC
Labels: duplicate
