### ISSUE TITLE
[WTexScan] Tool breaks when scanning UDMF maps.

### ISSUE THREAD

**Issue by inkoalawetrust** [MTrop/DoomTools#63] opened 2022-01-07 02:31 UTC
Running WTexScan on a UDMF map causes the tool to invariably output an error the moment it encounters the X coordinate value of the first thing in the index. This happens with every map, on line 4 of the maps' TEXTMAP lump, which is where the first X coordinate is stored.

Below I've got an example UDMF map to scan to reproduce the bug, but this happens with literally every other UDMF map too.

[wtexscanerror.zip](https://github.com/MTrop/DoomTools/files/7825915/wtexscanerror.zip)

![image](https://user-images.githubusercontent.com/56005600/148481781-7e6ec3a2-7517-4fdc-a553-e2f1ddbd5c5f.png)

**Comment by MTrop** [comment] 2022-01-08 04:51
That's strange - I can't reproduce it with your WAD:

![wtexscan](https://user-images.githubusercontent.com/5834131/148631894-3e2e4a34-dc25-454f-a463-e92c67a876c1.png)

What version of DoomTools do you have installed (you can get this by just typing `doomtools`)? It's possible that I may have inadvertently broken and fixed it again.

**Comment by MTrop** [comment] 2022-01-08 06:35
[Fixed in DoomStruct](https://github.com/MTrop/DoomStruct/releases/tag/2.14.1-RELEASE). Now I need confirmation on my "decimal separator" hunch.

**Comment by MTrop** [comment] 2022-01-08 17:53
Verified with running under a German locale: `-Duser.country=DE -Duser.language=de`. Thanks, **Micolah!**

**Comment by inkoalawetrust** [comment] 2022-01-08 18:53
My OS has Greek as the regional format. While everything else is in US English.

**Comment by MTrop** [comment] 2022-01-08 23:35
A release was made that fixes this: https://github.com/MTrop/DoomTools/releases/tag/2022.01.08-RELEASE

Closing ticket. Please re-open if the problem persists on the new version.

**Closed by MTrop** 2022-01-08 23:35 UTC
Labels: bug, high priority, dependent on 3rd party
